spec:
  template:
    spec:
      containers:
        - env:
          - name: FALLBACK
            valueFrom:
             configMapKeyRef:
                name: my-configmap
                key: fallback
